### ISSUE TITLE
Drills not working!

### ISSUE THREAD

**Issue by DARK-DarkSlayer** [TFlippy/kag_territorycontrol#37] opened 2019-08-15 04:12 UTC
Drills after the vanilla drill build, drills stopped working properly in TC, they only break blocks now, everything else, it can't break. Such things include the following: Doors, buildings(quarters, factionbases, chickencoops), trees, characters(players, chickens, pigs), tanks, etc. Anything that is an entity(non-transparent-solid blocks).

@TFlippy

**Comment by Vam-Jam** [comment] 2019-08-15 09:43
This could probably be caused by the build level changes that happened for the engi class. I doubt vanilla would have done this

**Comment by HKGx** [comment] 2019-08-19 20:39
@Vam-Jam 
drills stopped working properly after 3007 update iirc.

**Comment by DARK-DarkSlayer** [comment] 2019-09-08 01:33
The update when drills had heat indicators iirc

**Comment by TFlippy** [comment] 2019-12-15 20:31
Fixed a long time ago, forgot to close this.

**Closed as completed by TFlippy** 2019-12-15 20:31 UTC
